# Generated by labman from dut olimex-a20

import tbot
from tbot.machine import board, channel, connector, linux
from tbot.tc import git, shell, uboot
from flash import Flash
from send import Send
from dli import Dli
from sdwire import Sdwire

class Olimex_A20UBootBuilder(uboot.UBootBuilder):
    name = "olimex-a20"
    defconfig = "A20-OLinuXino_MICRO_defconfig"
    toolchain = "armv7-a"

class Olimex_A20(
    connector.ConsoleConnector,
    board.PowerControl,
    board.Board,
    Flash,
    Send,
    Dli,
    Sdwire,
):
    name = "olimex-a20"
    desc = "olimex A20-OLinuXino-MICRO"
    block_device = "/dev/sdcard5"
    console_uart = "/dev/ttyusb_port13"
    dli_hostname = "192.168.4.19"
    dli_outlet = "4"
    dli_password = "1234"
    dli_user = "admin"
    sdwire_serial = "sdwireda2"
    send_device = "/dev/usbdev-olimex-a20"
    usbboot_loadaddr = 0x4a000000
    usbboot_port = "4-10.4.4"

    ether_mac = None

    def poweron(self) -> None:
        """Procedure to turn power on."""
        self.sdwire_dut()
        self.dli_reset()

    def poweroff(self) -> None:
        """Procedure to turn power off."""
        self.dli_off()
        self.sdwire_ts()

    def connect(self, mach) -> channel.Channel:
        """Connect to the board's serial interface."""
        return mach.open_channel("picocom", "-q", "-b", "115200",
                                 self.console_uart)

    def flash(self, repo: git.GitRepository) -> None:
        self.sdwire_ts()
        self.flash_sunxi(repo)
        self.sdwire_dut()

    def send(self, repo: git.GitRepository) -> None:
        self.sdwire_ts()
        self.dli_reset()
        self.send_sunxi(repo)
        self.sdwire_dut()


class Olimex_A20UBoot(
    board.Connector,
    board.UBootAutobootIntercept,
    board.UBootShell,
):
    prompt = "=> "
    build = Olimex_A20UBootBuilder()


class Olimex_A20Linux(
    board.Connector,
    board.LinuxBootLogin,
    linux.Bash,
):
    username = ""
    password = ""


BOARD = Olimex_A20
UBOOT = Olimex_A20UBoot
LINUX = Olimex_A20Linux
