# Generated by labman from dut pcduino3_nano

import tbot
from tbot.machine import board, channel, connector, linux
from tbot.tc import git, shell, uboot
from flash import Flash
from send import Send
from sdwire import Sdwire
from ykush import Ykush

class Pcduino3_NanoUBootBuilder(uboot.UBootBuilder):
    name = "pcduino3_nano"
    defconfig = "Linksprite_pcDuino3_Nano_defconfig"
    toolchain = "armv7-a"

class Pcduino3_Nano(
    connector.ConsoleConnector,
    board.PowerControl,
    board.Board,
    Flash,
    Send,
    Sdwire,
    Ykush,
):
    name = "pcduino3_nano"
    desc = "Linksprite pcDuino3 Nano"
    block_device = "/dev/sdcard4"
    console_uart = "/dev/ttyusb_port12"
    sdwire_serial = "sdwireda1"
    ykush_port = "1"
    ykush_serial = "YK18511"

    ether_mac = "xx"

    def poweron(self) -> None:
        """Procedure to turn power on."""
        self.sdwire_dut()
        self.ykush_reset()

    def poweroff(self) -> None:
        """Procedure to turn power off."""
        self.ykush_off()
        self.sdwire_ts()

    def connect(self, mach) -> channel.Channel:
        """Connect to the board's serial interface."""
        return mach.open_channel("picocom", "-q", "-b", "115200",
                                 self.console_uart)

    def flash(self, repo: git.GitRepository) -> None:
        self.sdwire_ts()
        self.flash_sunxi(repo)
        self.sdwire_dut()

    def send(self, repo: git.GitRepository) -> None:
        self.sdwire_ts()
        self.ykush_reset()
        self.send_None(repo)
        self.sdwire_dut()


class Pcduino3_NanoUBoot(
    board.Connector,
    board.UBootAutobootIntercept,
    board.UBootShell,
):
    prompt = "=> "
    build = Pcduino3_NanoUBootBuilder()


class Pcduino3_NanoLinux(
    board.Connector,
    board.LinuxBootLogin,
    linux.Bash,
):
    username = ""
    password = ""


BOARD = Pcduino3_Nano
UBOOT = Pcduino3_NanoUBoot
LINUX = Pcduino3_NanoLinux
