# Generated by labman from dut rpi0

import tbot
from tbot.machine import board, channel, connector, linux
from tbot.tc import git, shell, uboot
from flash import Flash
from send import Send
from sdwire import Sdwire
from ykush import Ykush

class Rpi0UBootBuilder(uboot.UBootBuilder):
    name = "rpi0"
    defconfig = "rpi_0_w_defconfig"
    toolchain = "armv7-a"

class Rpi0(
    connector.ConsoleConnector,
    board.PowerControl,
    board.Board,
    Flash,
    Send,
    Sdwire,
    Ykush,
):
    name = "rpi0"
    desc = "Raspberry Pi 0 RaspiOS Bullseye Lite"
    console_uart = "/dev/ttyusb_port25"
    mount_point = "rpi0_b_boot"
    mount_uuid = "C839-E506"
    sdwire_serial = "da66"
    ykush_port = "3"
    ykush_serial = "YK19193"

    ether_mac = None

    def poweron(self) -> None:
        """Procedure to turn power on."""
        self.sdwire_dut()
        self.ykush_reset()

    def poweroff(self) -> None:
        """Procedure to turn power off."""
        self.ykush_off()
        self.sdwire_ts()

    def connect(self, mach) -> channel.Channel:
        """Connect to the board's serial interface."""
        return mach.open_channel("picocom", "-q", "-b", "115200", self.console_uart)

    def flash(self, repo: git.GitRepository) -> None:
        self.sdwire_ts()
        self.flash_rpi0(repo)
        self.sdwire_dut()

    def send(self, repo: git.GitRepository) -> None:
        self.sdwire_ts()
        self.ykush_reset()
        self.send_None(repo)
        self.sdwire_dut()


class Rpi0UBoot(
    board.Connector,
    board.UBootAutobootIntercept,
    board.UBootShell,
):
    prompt = "U-Boot> "
    build = Rpi0UBootBuilder()


class Rpi0Linux(
    board.Connector,
    board.LinuxBootLogin,
    linux.Bash,
):
    username = "pi"
    password = "raspberry"


BOARD = Rpi0
UBOOT = Rpi0UBoot
LINUX = Rpi0Linux
