# Generated by labman from dut rpi4

import tbot
from tbot.machine import board, channel, connector, linux
from tbot.tc import git, shell, uboot
from flash import Flash
from send import Send
from dli import Dli
from sdwire import Sdwire
from usbrelay import Usbrelay

class Rpi4UBootBuilder(uboot.UBootBuilder):
    name = "rpi4"
    defconfig = "rpi_4_defconfig"
    toolchain = "aarch64"

class Rpi4(
    connector.ConsoleConnector,
    board.PowerControl,
    board.Board,
    Flash,
    Send,
    Dli,
    Sdwire,
    Usbrelay,
):
    name = "rpi4"
    desc = "Raspberry Pi 4 Ubuntu"
    block_device = "/dev/sdcard13"
    console_uart = "/dev/ttyusb_port24"
    dli_hostname = "192.168.4.27"
    dli_outlet = "6"
    dli_password = "1234"
    dli_user = "admin"
    mount_point = "rpi4_boot"
    mount_uuid = "6B58-81F8"
    sdwire_serial = "da65"
    usbrelay_name = "8QMBS"
    usbrelay_reset = "5"

    ether_mac = None

    def poweron(self) -> None:
        """Procedure to turn power on."""
        self.sdwire_dut()
        self.dli_reset()
        self.usbrelay_toggle_reset()

    def poweroff(self) -> None:
        """Procedure to turn power off."""
        self.dli_off()
        self.sdwire_ts()

    def connect(self, mach) -> channel.Channel:
        """Connect to the board's serial interface."""
        return mach.open_channel("picocom", "-q", "-b", "115200", self.console_uart)

    def flash(self, repo: git.GitRepository) -> None:
        self.sdwire_ts()
        self.flash_rpi4(repo)
        self.sdwire_dut()

    def send(self, repo: git.GitRepository) -> None:
        self.sdwire_ts()
        self.dli_reset()
        self.send_None(repo)
        self.sdwire_dut()


class Rpi4UBoot(
    board.Connector,
    board.UBootAutobootIntercept,
    board.UBootShell,
):
    prompt = "U-Boot> "
    build = Rpi4UBootBuilder()


class Rpi4Linux(
    board.Connector,
    board.LinuxBootLogin,
    linux.Bash,
):
    username = "pi"
    password = "raspberry"


BOARD = Rpi4
UBOOT = Rpi4UBoot
LINUX = Rpi4Linux
