# Generated by labman from dut sn9260

import tbot
from tbot.machine import board, channel, connector, linux
from tbot.tc import git, shell, uboot
from flash import Flash
from send import Send
from usbrelay import Usbrelay

class Sn9260UBootBuilder(uboot.UBootBuilder):
    name = "sn9260"
    defconfig = "snapper9260_defconfig"
    toolchain = "armv7-a"

class Sn9260(
    connector.ConsoleConnector,
    board.PowerControl,
    board.Board,
    Flash,
    Send,
    Usbrelay,
):
    name = "sn9260"
    desc = "Snapper 9260"
    console_uart = "192.168.4.23:2003"
    send_device = "/dev/usbdev-sn9260"
    usbboot_loadaddr = 0x21f00000
    usbboot_port = "1-3.1.1"
    usbrelay_name = "7QMBS"
    usbrelay_recovery = "3"
    usbrelay_reset = "2"

    ether_mac = None

    def poweron(self) -> None:
        """Procedure to turn power on."""
        self.usbrelay_toggle_reset()

    def poweroff(self) -> None:
        """Procedure to turn power off."""
        pass

    def connect(self, mach) -> channel.Channel:
        """Connect to the board's serial interface."""
        return mach.open_channel("bash", "-c", "stty raw; nc 192.168.4.23 2003")

    def flash(self, repo: git.GitRepository) -> None:
        self.flash_at91(repo)

    def send(self, repo: git.GitRepository) -> None:
        self.usbrelay_set_recovery(True)
        self.usbrelay_set_reset(True)
        self.usbrelay_delay()
        self.usbrelay_set_reset(False)
        self.usbrelay_delay()
        self.usbrelay_set_recovery(False)
        self.send_at91(repo)


class Sn9260UBoot(
    board.Connector,
    board.UBootAutobootIntercept,
    board.UBootShell,
):
    prompt = "=> "
    build = Sn9260UBootBuilder()


class Sn9260Linux(
    board.Connector,
    board.LinuxBootLogin,
    linux.Bash,
):
    username = ""
    password = ""


BOARD = Sn9260
UBOOT = Sn9260UBoot
LINUX = Sn9260Linux
