# Generated by labman from dut tk1

import tbot
from tbot.machine import board, channel, connector, linux
from tbot.tc import git, shell, uboot
from flash import Flash
from usbrelay import Usbrelay

class Tk1UBootBuilder(uboot.UBootBuilder):
    name = "tk1"
    defconfig = "jetson-tk1_defconfig"
    toolchain = "armv7-a"

class Tk1(
    connector.ConsoleConnector,
    board.PowerControl,
    board.Board,
    Flash,
    Usbrelay,
):
    name = "tk1"
    desc = "Jetson TK1"
    console_uart = "/dev/ttyusb_port3"
    usbrelay_name = "6QMBS"
    usbrelay_power_button = "1"
    usbrelay_recovery = "3"
    usbrelay_reset = "2"

    ether_mac = None

    def poweron(self) -> None:
        """Procedure to turn power on."""
        self.usbrelay_toggle_reset()

    def poweroff(self) -> None:
        """Procedure to turn power off."""
        pass

    def connect(self, mach) -> channel.Channel:
        """Connect to the board's serial interface."""
        return mach.open_channel("picocom", "-q", "-b", "115200",
                                 self.console_uart)

    def flash(self, repo: git.GitRepository) -> None:
        self.flash_tegra(repo)


class Tk1UBoot(
    board.Connector,
    board.UBootAutobootIntercept,
    board.UBootShell,
):
    prompt = "=> "
    build = Tk1UBootBuilder()


class Tk1Linux(
    board.Connector,
    board.LinuxBootLogin,
    linux.Bash,
):
    username = ""
    password = ""


BOARD = Tk1
UBOOT = Tk1UBoot
LINUX = Tk1Linux
