# Generated by labman from dut tk1

import time

import tbot
from tbot.machine import board, channel, connector, linux
from tbot.tc import git, shell, uboot
from flash import Flash
from usbrelay import Usbrelay

class Tk1UBootBuilder(uboot.UBootBuilder):
    name = "tk1"
    defconfig = "jetson-tk1_defconfig"
    toolchain = "armv7-a"

class Tk1(
    connector.ConsoleConnector,
    board.PowerControl,
    board.Board,
    Flash,
    Usbrelay,
):
    name = "tk1"
    desc = "Jetson TK1"
    console_uart = "/dev/ttyusb_port3"
    usbrelay_name = "6QMBS"
    usbrelay_power_button = "1"
    usbrelay_recovery = "3"
    usbrelay_reset = "2"

    tegra_device = "/dev/usbdev-jetson-tk1"
    tegra_bct = "/vid/software/devel/tegra/tegra-uboot-flasher-scripts/jetson-tk1/PM375_Hynix_2GB_H5TC4G63AFR_RDA_924MHz.bct"
    tegra_loadaddr = 0x80108000
    tegra_port = "4-10.1.1"

    ether_mac = None

    def poweron(self) -> None:
        """Procedure to turn power on."""
        #self.usbrelay_toggle_reset()
        pass

    def poweroff(self) -> None:
        """Procedure to turn power off."""
        pass

    def connect(self, mach) -> channel.Channel:
        """Connect to the board's serial interface."""
        return mach.open_channel("picocom", "-q", "-b", "115200",
                                 self.console_uart)

    def flash(self, repo: git.GitRepository) -> None:
        self.usbrelay_set_recovery(True)
        self.usbrelay_set_reset(True)
        time.sleep(.1)
        self.usbrelay_set_reset(False)
        time.sleep(.1)
        self.usbrelay_set_recovery(False)
        self.flash_tegra(repo)


class Tk1UBoot(
    board.Connector,
    board.UBootAutobootIntercept,
    board.UBootShell,
):
    prompt = "=> "
    build = Tk1UBootBuilder()


class Tk1Linux(
    board.Connector,
    board.LinuxBootLogin,
    linux.Bash,
):
    username = ""
    password = ""


BOARD = Tk1
UBOOT = Tk1UBoot
LINUX = Tk1Linux
