# Generated by labman from dut zynq_zybo

import tbot
from tbot.machine import board, channel, connector, linux
from tbot.tc import git, shell, uboot
from flash import Flash
from dli import Dli
from sdwire import Sdwire
from usbrelay import Usbrelay

class Zynq_ZyboUBootBuilder(uboot.UBootBuilder):
    name = "zynq_zybo"
    defconfig = "zynq_zybo_defconfig"
    toolchain = "armv7-a"

class Zynq_Zybo(
    connector.ConsoleConnector,
    board.PowerControl,
    board.Board,
    Flash,
    Dli,
    Sdwire,
    Usbrelay,
):
    name = "zynq_zybo"
    desc = "Zynq Zybo"
    console_uart = "/dev/ttyusb_port5"
    dli_hostname = "192.168.4.19"
    dli_outlet = "5"
    dli_password = "1234"
    dli_user = "admin"
    mount_point = "zynq_zybo_boot"
    mount_uuid = "5203-DB74"
    sdwire_serial = "202001064001"
    usbrelay_name = "6QMBS"
    usbrelay_reset = "6"

    ether_mac = None

    def poweron(self) -> None:
        """Procedure to turn power on."""
        self.sdwire_dut()
        self.dli_reset()
        self.usbrelay_toggle_reset()

    def poweroff(self) -> None:
        """Procedure to turn power off."""
        self.dli_off()
        self.sdwire_ts()

    def connect(self, mach) -> channel.Channel:
        """Connect to the board's serial interface."""
        self.dli_on()
        self.wait_for_uart(0.7)
        return mach.open_channel("picocom", "-q", "-b", "115200",
                                 self.console_uart)

    def flash(self, repo: git.GitRepository) -> None:
        self.sdwire_ts()
        self.flash_zynq(repo)
        self.sdwire_dut()


class Zynq_ZyboUBoot(
    board.Connector,
    board.UBootAutobootIntercept,
    board.UBootShell,
):
    prompt = "Zynq> "
    build = Zynq_ZyboUBootBuilder()


class Zynq_ZyboLinux(
    board.Connector,
    board.LinuxBootLogin,
    linux.Bash,
):
    username = ""
    password = ""


BOARD = Zynq_Zybo
UBOOT = Zynq_ZyboUBoot
LINUX = Zynq_ZyboLinux
